### PR TITLE
esn-frontend-calendar#12: Fixed broken search back button

### LINKED ISSUE #12: search back button is broken
## Reproduction steps

* go on calendar
* search for something
* click on the "back" icon 

### current behaviour

The back button does not work

### intended behaviour

The back button sends me back to the calendar view

Warning: also test when there is no history. Example: point your browser to http://localhost:9900/#/search/?q=test&p=op.events , then hit the back button: it should go to the default calendar grid view

### PR DESCRIPTION
**Pull request by itswillta**
This PR is to resolve https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/12.

Demo: Please refer to https://github.com/OpenPaaS-Suite/esn-frontend-calendar/pull/32.

### CODE REVIEW

File: src/frontend/js/modules/previous-page.js [hunk 1]
```diff
@@ -1,26 +1,23 @@
...
   })
 
-  .directive('esnBackButton', function(esnPreviousPage) {
+  .directive('esnBackButton', function(esnPreviousPage, $state) {
     return {
       restrict: 'A',
-      link: function(scope, element, attrs) {
+      link: function(scope, element) {
+        // TODO: Write tests for the newly changed logic https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/12
+        const defaultState = $state.get().find(state => state.default).name;
```
Comment (itswillta) [inline src/frontend/js/modules/previous-page.js]: This means we'll have to manually add `default: true` to the default state in each SPA (if the SPA is using `esn-back-button`). For now, only the `esn-frontend-calendar` SPA uses `esn-back-button`, so that's the only place we're going to add it.

File: src/frontend/js/modules/previous-page.js [hunk 2]
```diff
@@ -1,26 +1,23 @@
...
-
-  angular.module('esn.previous-page', [])
+angular.module('esn.previous-page', [])
 
   .run(function(esnPreviousPage) {
     esnPreviousPage.init();
   })
 
-  .directive('esnBackButton', function(esnPreviousPage) {
+  .directive('esnBackButton', function(esnPreviousPage, $state) {
```
Comment (tuanlc) [inline src/frontend/js/modules/previous-page.js]:
```suggestion
  .directive('esnBackButton', function($state, esnPreviousPage) {
```

File: src/frontend/js/modules/previous-page.js (hunk 1 above)
Comment (tuanlc) [reply src/frontend/js/modules/previous-page.js]: Should we have the default one. `home` for example.

**Comment by huy-ta** [comment]
> Should we have the default one. home for example.

I tweaked it a little bit to also allow the default `home` state to work (if there's one). Please check the first commit.

File: src/frontend/js/modules/previous-page.js (hunk 2 above)
Comment (itswillta) [reply src/frontend/js/modules/previous-page.js]: Fixed.

File: src/frontend/js/modules/previous-page.js (hunk 1 above)
Comment (itswillta) [reply src/frontend/js/modules/previous-page.js]: I tweaked it a little bit to also allow the state provided from the attribute to work (if there's one). Please check the second commit.

File: src/frontend/js/modules/previous-page.js [hunk 3]
```diff
@@ -1,26 +1,28 @@
...
+  .directive('esnBackButton', function($state, esnPreviousPage) {
     return {
       restrict: 'A',
       link: function(scope, element, attrs) {
+        // TODO: Write tests for the newly changed logic https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/12
+        const availableStates = $state.get();
+        const backState = availableStates.find(state => state.name === attrs.esnBackButton) || availableStates.find(state => state.default);
+
+        if (!backState) {
+          return console.error(`There is no ${attrs.esnBackButton} state or a default state to come back to.`)
```
Comment (tuanlc) [inline src/frontend/js/modules/previous-page.js]: use `$log` instead

Comment (itswillta) [reply src/frontend/js/modules/previous-page.js]: Fixed.

**Review by tuanlc — APPROVED** [review]

**Review by rezk2ll — APPROVED** [review]

**Review by chamerling — APPROVED** [review]
