### PR TITLE
OpenPaaS-Suite/esn-frontend-inbox#128 add support for not using history.back

### LINKED ISSUE #128: Closing email composer is wrong on mobile
On mobile, compose an email and discard it by clicking on the close button or send it: closes the composer but do like some history.back which does not resolve a inbox state. When opening inbox by setting the URL when I was browsing just before on http://something, closing the composer closes inbox and reopen http://something

inbox

### PR DESCRIPTION
**Pull request by rezk2ll**
the idea is to use a directive to specify that we don't want to use `history.back`

```pug
button.btn.btn-link.btn-icon.close.button.visible-xs(prevent-history-back='', href='', esn-back-button='unifiedinbox.inbox')
```

closes https://github.com/OpenPaaS-Suite/esn-frontend-inbox/issues/128

### CODE REVIEW

**Review by fabienmoyon — DISMISSED** [review]

File: src/frontend/js/modules/previous-page.js [hunk 1]
```diff
@@ -11,12 +11,13 @@ angular.module('esn.previous-page', [])
         // TODO: Write tests for the newly changed logic: https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/12, https://github.com/OpenPaaS-Suite/esn-frontend-inbox/issues/74
```
Comment (itswillta) [inline src/frontend/js/modules/previous-page.js]: Edit the comment so that we write tests for these later :trollface:

File: src/frontend/js/modules/previous-page.js [hunk 2]
```diff
@@ -11,12 +11,13 @@ angular.module('esn.previous-page', [])
...
         const availableStates = $state.get();
         const backState = availableStates.find(state => state.name === attrs.esnBackButton) || availableStates.find(state => state.default);
+        const preventHistoryBack = attrs.hasOwnProperty('preventHistoryBack') || false;
```
Comment (itswillta) [inline src/frontend/js/modules/previous-page.js]:
```suggestion
        const preventHistoryBack = attrs.hasOwnProperty('preventHistoryBack');
```

**Comment by itswillta** [comment]
Rebase the branch.

**Comment by rezk2ll** [comment]
> Rebase the branch.

done

File: src/frontend/js/modules/previous-page.js (hunk 1 above)
Comment (rezk2ll) [reply src/frontend/js/modules/previous-page.js]: create an issue for that

**Comment by huy-ta** [comment]
You pressed the "Resolve discussion" for my my comment but you didn't change the code accordingly :disappointed:.

**Review by itswillta — DISMISSED** [review]
Show me the issue that you've created to remind people to write tests for these changes :trollface:.

**Comment by rezk2ll** [comment]
> Show me the issue that you've created to remind people to write tests for these changes :trollface:.

https://github.com/OpenPaaS-Suite/esn-frontend-common-libs/issues/132 and added to the September board

**Comment by tuanlc** [comment]
> #132 and added to the September board

Why did you not write in the same PR?

**Review by tuanlc — APPROVED** [review]

**Review by itswillta — APPROVED** [review]

**Review by MichaelBailly — APPROVED** [review]
