### PR TITLE
fixed the header template not using the provided API url for the theme logo

### LINKED ISSUE #197: fix the platform logo and avatar api endpoint
should use the OPENPAAS_API_URL provided in the openpaas.js env file instead of the current location.

### PR DESCRIPTION
**Pull request by rezk2ll**

### CODE REVIEW

File: src/frontend/js/modules/header/header.js [hunk 1]
```diff
@@ -114,6 +114,7 @@
           };
 
           scope.domainId = session.domain._id;
+          scope.apiURL = window.openpaas && window.openpaas.OPENPAAS_API_URL || '';
```
Comment (fabienmoyon) [inline src/frontend/js/modules/header/header.js]: rename it `baseUrl` like here https://github.com/linagora/esn-frontend-common-libs/blob/43972a3af0775899526b030cb32e94b011f23300/src/frontend/js/modules/http.js#L102

File: src/frontend/views/modules/header/header.pug [hunk 2]
```diff
@@ -6,7 +6,7 @@ div
       ul.list-inline.all-centered
         li.logo
           a(href='', ui-sref='home')
-            img.openpaas-logo(ng-src="{{'/api/themes/' + domainId + '/logo'}}", fallback-src='/images/white-logo.svg', src="/images/white-logo.svg", alt="{{ 'OpenPaas Logo' | translate }}")
+            img.openpaas-logo(ng-src="{{apiURL + '/api/themes/' + domainId + '/logo'}}", fallback-src='/images/white-logo.svg', src="/images/white-logo.svg", alt="{{ 'OpenPaas Logo' | translate }}")
```
Comment (fabienmoyon) [inline src/frontend/views/modules/header/header.pug]: we also need to do it for the `favicon` here https://github.com/linagora/esn-frontend-common-libs/blob/43972a3af0775899526b030cb32e94b011f23300/src/frontend/views/modules/sidebar/contextual-sidebar.pug#L10

**Review by fabienmoyon — DISMISSED** [review]

**Review by tanandy — DISMISSED** [review]

**Review by tanandy — APPROVED** [review]

**Review by renaudboyer — APPROVED** [review]
