### PR TITLE
esn-frontend-calendar#160 added supported moment locale mapping

### LINKED ISSUE #160: fix moment.locale not working when you provide zh as the desired locale
please refer to: https://github.com/OpenPaaS-Suite/esn-frontend-calendar/pull/146#discussion_r499322187

TODO:

**1**: map locales supported by ESN ( zh, fr, ru etc...) and require them so they can be used when we use `moment.locale`.

**2**: fix the service providing locales to provide `cn-zh` instead of `zh` ( `esnI18nService.getLocale();` ) or provide another function instead if the changes break other components. this is due to `moment.locale('zh')` will not work and should be `moment.locale('cn-zh')`

### PR DESCRIPTION
**Pull request by rezk2ll**
partially resolves https://github.com/OpenPaaS-Suite/esn-frontend-calendar/issues/160

### CODE REVIEW

File: src/frontend/js/modules/i18n/i18n.constants.js [hunk 1]
```diff
@@ -38,5 +38,12 @@
       vi: 'EEE dd/MM/yyyy',
       zh: 'EEE yyyy/MM/dd',
       ru: 'EEE dd/MM/yyyy'
+    })
+    .constant('ESN_I18N_SUPPORTED_LOCALES_MAPPING', {
```
Comment (itswillta) [inline src/frontend/js/modules/i18n/i18n.constants.js]:
```suggestion
    .constant('ESN_I18N_SUPPORTED_MOMENT_LOCALES_MAPPING', {
```

**Review by itswillta — APPROVED** [review]

**Review by asmaNode — APPROVED** [review]
