### PR TITLE
OpenPaaS-Suite/esn-frontend-contacts#36 Fix form text overlay

### LINKED ISSUE #36: UI/Create new address book/Placeholder is still shown when user inputs the address book name
See screenshot

### PR DESCRIPTION
**Pull request by pbson**
Fix: https://github.com/OpenPaaS-Suite/esn-frontend-contacts/issues/36

### CODE REVIEW

File: src/frontend/components/material-admin/js/modules/form.js [hunk 1]
```diff
@@ -12,7 +12,7 @@ materialAdmin
         return {
             restrict: 'C',
             link: function(scope, element) {
-                if($('.fg-line')[0]) {
```
Comment (piavgh) [inline src/frontend/components/material-admin/js/modules/form.js:15]: did you check the code in the old project to see if why this index [0] worked previously?

Comment (itswillta) [reply src/frontend/components/material-admin/js/modules/form.js:15]: @pbson `$('.fg-line')` will always exist I suppose (as a jQuery object). The real element that you want to find is `$('.fg-line')[0]`.

Comment (pbson) [reply src/frontend/components/material-admin/js/modules/form.js:15]: @huy-ta For some reason `$('.fg-line')[0]` is undefined, but `$('.fg-line').first()` works, so I think I'm gonna change it to that. What's your opinion?

Comment (itswillta) [reply src/frontend/components/material-admin/js/modules/form.js:15]: `first()` will also always be a jQuery object, so it will always exist even if the element isn't found.

Comment (MichaelBailly) [reply src/frontend/components/material-admin/js/modules/form.js:15]: For everybody: 
1/ the original code is very dirty. Basically it means "if there is at least one element on the whole page that has the `fg-line' class. I know this is material admin code and not ours, but still it's ugly.

2/ the condition $('.fg-line') will ALWAYS BE TRUE. Because what is returned will be a jQuery object. That jQuery object may contains 0 elements, still it's an object, so it will be evaluated to truthy.

Comment (MichaelBailly) [reply src/frontend/components/material-admin/js/modules/form.js:15]: Can you try with `element.closest('.fg-line').length` ?

Comment (pbson) [reply src/frontend/components/material-admin/js/modules/form.js:15]: OK I'll try it. Thank you. For some reason `$(.fg-line)[0]` does exist when using browser console, but return undefined when I try to console log it from the code

Comment (piavgh) [reply src/frontend/components/material-admin/js/modules/form.js:15]: @pbson: maybe it's "evaluated just now". You might recognize it by an exclamation mark next to the log. It means when the console.log statement runs, the value is undefined. But after that, the value is evaluated. But it's just a guess

Comment (MichaelBailly) [reply src/frontend/components/material-admin/js/modules/form.js:15]: Maybe we can process differently. In Inbox, Click on "New folder": the new folder form is in a modal and uses fg-line, and it got the blue line working fine. Maybe you can spot the difference from here... ?

**Review by MichaelBailly — APPROVED** [review]

**Review by rezk2ll — APPROVED** [review]
